# Generated by Django 5.2.14 on 2026-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap_fuel", "SAP fuel & procurement"),
                            ("utility_electricity", "Utility electricity"),
                            ("travel_concur", "Corporate travel (Concur-shape)"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("original_filename", models.CharField(max_length=300)),
                ("file_blob", models.FileField(upload_to="uploads/%Y/%m/")),
                ("parser_version", models.CharField(default="v1", max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parse_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="parser-emitted summary: detected encoding, locale, schema match score",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RawRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField()),
                ("raw_json", models.JSONField()),
                ("parse_errors", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["batch_id", "line_no"],
            },
        ),
    ]
