# Generated by Django 5.2.14 on 2026-05-24 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionbatch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ingestionbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rawrow",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_rows",
                to="ingestion.ingestionbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionbatch",
            index=models.Index(
                fields=["tenant", "source_type", "-uploaded_at"],
                name="ingestion_i_tenant__6065b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawrow",
            index=models.Index(
                fields=["batch", "line_no"], name="ingestion_r_batch_i_824136_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "line_no"), name="uniq_rawrow_per_batch_line"
            ),
        ),
    ]
