# Generated by Django 5.2.14 on 2026-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "iata",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("icao", models.CharField(blank=True, max_length=4)),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "country",
                    models.CharField(
                        db_index=True, help_text="ISO-3166-1 alpha-2", max_length=2
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
            options={
                "ordering": ["iata"],
            },
        ),
        migrations.CreateModel(
            name="PlantLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("werks_code", models.CharField(max_length=8)),
                ("site_name", models.CharField(max_length=200)),
                (
                    "country",
                    models.CharField(help_text="ISO-3166-1 alpha-2", max_length=2),
                ),
                (
                    "grid_region",
                    models.CharField(
                        blank=True,
                        help_text="eGRID subregion / DEFRA region for Scope 2 join",
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
