# Generated by Django 5.2.14 on 2026-05-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantlookup",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plants",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="plantlookup",
            index=models.Index(
                fields=["tenant", "werks_code"], name="reference_p_tenant__0b0651_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantlookup",
            unique_together={("tenant", "werks_code")},
        ),
    ]
