# Generated by Django 5.2.14 on 2026-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                (
                    "ghg_category",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. Stationary Combustion, Purchased Electricity, Business Travel - Air",
                        max_length=64,
                    ),
                ),
                ("activity_type", models.CharField(db_index=True, max_length=64)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_canonical",
                    models.CharField(
                        help_text="L, kWh, km, room-night, ...", max_length=24
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "location_country",
                    models.CharField(
                        blank=True, help_text="ISO-3166-1 alpha-2", max_length=2
                    ),
                ),
                (
                    "location_region",
                    models.CharField(
                        blank=True,
                        help_text="eGRID subregion / DEFRA region / state",
                        max_length=32,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="source-specific attributes: plant_code, cabin_class, supplier, meter_id, ...",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("flagged", "Flagged (needs attention)"),
                            ("edited", "Edited by analyst"),
                            ("approved", "Approved (locked for audit)"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "confidence_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="list of {code, severity, message, field?}",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_edited_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap_fuel", "SAP fuel & procurement"),
                            ("utility_electricity", "Utility electricity"),
                            ("travel_concur", "Corporate travel"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "match_field",
                    models.CharField(
                        help_text="raw column name, e.g. MATNR, MATKL, SAKTO, RATE_CLASS, EXPENSE_TYPE",
                        max_length=64,
                    ),
                ),
                (
                    "match_pattern",
                    models.CharField(
                        help_text="exact match (case-insensitive)", max_length=200
                    ),
                ),
                ("mapped_activity_type", models.CharField(max_length=64)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["tenant", "source_type", "match_field"],
            },
        ),
    ]
