# Generated by Django 5.2.14 on 2026-05-24 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0002_initial"),
        ("normalization", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activityrecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="source_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_records",
                to="ingestion.ingestionbatch",
            ),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="source_row",
            field=models.OneToOneField(
                blank=True,
                help_text="Some derived rows (e.g. period-split utility) have no single source row.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_record",
                to="ingestion.rawrow",
            ),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_records",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="classificationrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classificationrule",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classification_rules",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["tenant", "status"], name="normalizati_tenant__fc9d15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["tenant", "scope", "period_start"],
                name="normalizati_tenant__77d1c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["source_batch", "status"], name="normalizati_source__3ecb84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["activity_type"], name="normalizati_activit_3e1cc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationrule",
            index=models.Index(
                fields=["tenant", "source_type", "match_field", "active"],
                name="normalizati_tenant__e28c97_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classificationrule",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_type", "match_field", "match_pattern"),
                name="uniq_rule_per_tenant_source_field_pattern",
            ),
        ),
    ]
