# Generated by Django 5.2.14 on 2026-05-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_initial"),
        ("normalization", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityrecord",
            name="source_row",
            field=models.ForeignKey(
                blank=True,
                help_text="Multiple records per raw row possible (period-split utility, multi-segment travel).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_records",
                to="ingestion.rawrow",
            ),
        ),
    ]
