# Generated by Django 5.2.14 on 2026-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kgco2e", models.DecimalField(decimal_places=4, max_digits=18)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. diesel, petrol, lpg, electricity_grid, air_travel_economy, hotel_night, rental_car_small",
                        max_length=64,
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO-2 country, or grid subregion (e.g. US-CAMX, GB, DE)",
                        max_length=16,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "scope",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("location", "Location-based"),
                            ("market", "Market-based"),
                            ("direct", "Direct (Scope 1 or 3 fuel-based)"),
                        ],
                        default="direct",
                        max_length=16,
                    ),
                ),
                (
                    "factor_kgco2e",
                    models.DecimalField(
                        decimal_places=6, help_text="kg CO2e per unit", max_digits=14
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="canonical unit, e.g. L, kWh, passenger-km, room-night",
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("defra", "DEFRA / BEIS (UK)"),
                            ("egrid", "EPA eGRID (US)"),
                            ("chsb", "Cornell CHSB (hotels)"),
                            ("iea", "IEA grid factors"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["activity_type", "region_code", "year"],
                        name="emissions_e_activit_187afd_idx",
                    ),
                    models.Index(
                        fields=["scope", "method"], name="emissions_e_scope_713543_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity_type", "region_code", "year", "method"),
                        name="uniq_factor_per_activity_region_year_method",
                    )
                ],
            },
        ),
    ]
