# Generated by Django 5.2.14 on 2026-05-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emissions", "0001_initial"),
        ("normalization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionresult",
            name="activity_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emission_result",
                to="normalization.activityrecord",
            ),
        ),
        migrations.AddField(
            model_name="emissionresult",
            name="factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="emissions.emissionfactor",
            ),
        ),
    ]
