# Generated by Django 5.2.14 on 2026-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("edit", "Edit (analyst field change)"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("flag", "Flag"),
                            ("bulk_approve", "Bulk approve"),
                            ("rule_apply", "Classification rule applied"),
                            ("parser_emit", "Parser created record"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("ts", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
    ]
